### ISSUE TITLE
list of integers, how do you terminate the list? and manage it neat like python?

### ISSUE THREAD

**Issue by muhammad-bin-zafar** [MidnQP/cpy#23]

**Comment by MidnQP** [comment]
One of the things we try to maintain is: compat with vanilla C. But in this case, it seems: we might need `void listAdd(float* list, float element)`.
```C
// You would do: 
float* list = new(t_list, 10);
listAdd(list, 4); // similar to: Array.push in javascript.

// Doing below won't be wise, and will break the cpy compat.
// Because this might create an empty space between the list.
list[2] = 2;
```
The whole point of `cpy` is to make C operations better and simpler, like jQuery did for JavaScript. Mark my words!

**Comment by MidnQP** [comment]
The List implementation uses `DBL_MAX` as a delimiter for numbers.
